imports :
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework :
    #esi:             ~
    translator              : { fallbacks: ["%bookarg.locale%"] }
    secret                  : "%bookarg.secret%"
    router :
        resource            : "%kernel.root_dir%/config/routing.yml"
        strict_requirements : ~
    form                    : ~
    csrf_protection         : ~
    validation              :      { enable_annotations: true }
    serializer              :      { enable_annotations: true }
    templating :
        engines             : ['twig']
        assets_version      : %bookarg.version%
    trusted_proxies         : ~
    default_locale          :  "%bookarg.locale%"
    session :
        handler_id          : ~
        cookie_lifetime     : 7200
        cookie_domain       : .%bookarg.host%
        name                : bookarg_s
        # handler_id set to null will use default session handler from php.ini
        # cookie_httponly: true
        # gc_maxlifetime: 900
        # gc_probability: 1
        # gc_divisor: 1
        # cookie_secure: true
    fragments                : ~
    http_method_override     : true

# Twig Configuration
twig :
    debug               : "%kernel.debug%"
    strict_variables    : "%kernel.debug%"
    form_themes :
        - 'GushhCoreBundle:Form:fields.html.twig'
    globals:
        version         : "%bookarg.version%"
        brand           : "%bookarg.brand%"
        tracking:
            google      : "%bookarg.tracking.google%"

# Assetic Configuration
assetic :
    debug              : "%kernel.debug%"
    use_controller     : false
    bundles            : [ ]
    #java              : /usr/bin/java
    filters            :
        cssrewrite     : ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine :
    dbal :
        driver   : pdo_mysql
        host     : "%db.host%"
        port     : "%db.port%"
        dbname   : "%db.name%"
        user     : "%db.user%"
        password : "%db.password%"
        charset  : UTF8
        options  :
            1002: 'SET sql_mode=(SELECT REPLACE(@@sql_mode, "ONLY_FULL_GROUP_BY", ""))'
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%db.path%"

    orm :
        auto_generate_proxy_classes : "%kernel.debug%"
        naming_strategy             : doctrine.orm.naming_strategy.underscore
        auto_mapping                : true

# Swiftmailer Configuration
swiftmailer :
    disable_delivery : false
    transport        : %mail.transport%
    host             : %mail.host%
    username         : %mail.user%
    password         : %mail.password%
    encryption       : %mail.encryption%
    port             : %mail.port%
    spool            : { type: memory }

jms_security_extra :
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services        : true

    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute     : false

    # Enables expression language
    expressions                : false

    # Allows you to disable some, or all built-in voters
    voters                     :
        disable_authenticated  : false
        disable_role           : false
        disable_acl            : false

    # Allows you to specify access control rules for specific methods, such
    # as controller actions
    method_access_control      : { }

    # util:
    #     secure_random:
    #         connection: # the doctrine connection name
    #         table_name: seed_table
    #         seed_provider: # service id of your own seed provider implementation

fos_user :
    db_driver     : orm                          # Required
    firewall_name : main                         # Required
    user_class    : Gushh\CoreBundle\Entity\User # Required
    service :
        mailer : fos_user.mailer.twig_swift
    resetting :
        email :
            template  : FOSUserBundle:Resetting:email.html.twig
            from_email :
                address     : %bookarg.email%
                sender_name : %bookarg.brand%

stof_doctrine_extensions :
    default_locale       : %bookarg.locale%
    translation_fallback : true
    orm:
        default:
            timestampable : true
            sluggable     : true

# PDF
knp_snappy :
    pdf :
        enabled : true
        binary  : /var/www/html/zohartours/wkhtmltopdf.sh
        options : []
    # image:
    #     enabled:    true
    #     binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
    #     options:    []

jms_i18n_routing :
    default_locale   : %bookarg.locale%
    locales          : [en, es]
    strategy         : custom
    redirect_to_host : true
    hosts :
        en           : "%bookarg.host.en%"
        es           : "%bookarg.host.es%"
