<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CancellationPolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CancellationPolicyRepository extends EntityRepository
{

    /**
     * Get all blackout dates
     *
     * @return array
     */
    public function findByHotel($hid)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:CancellationPolicy')
            ->createQueryBuilder('c')
            ->where('c.hotel = :hotel')
            ->setParameter('hotel', $hid)
            ->orderBy('c.name', 'ASC');
    }
}
