<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateRepository extends EntityRepository
{

    /**
     * [findDatesByRoomAndDays description]
     *
     * @author   Anibal Fernández   <anibaldfernandez@hotmail.com>
     *
     * @param    int $rid Room id
     * @param    array $days [description]
     *
     * @return   [type]   [description]
     */
    public function findDatesByRoomAndDays($rid, array $days, $nights)
    {
        $dates = $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Date')
            ->createQueryBuilder('d')
            ->where('d.room = :room')
            ->andWhere('d.date IN(:days)')
            ->andWhere('d.maximumStay >= :nights')
            ->andWhere('d.minimumStay <= :nights')
            ->orderBy('d.date', 'ASC')
            ->setParameter('room', $rid)
            ->setParameter('days', array_values($days))
            ->setParameter('nights', $nights)
            ->getQuery()
            ->getResult();

        // Si la cantidad de días devueltos es igual
        // a la cantidad de días solicitados retorna $dates
        return (count($dates) == count($days)) ? $dates : false;
    }


    /**
     * Get all blackout dates
     *
     * @return array
     */
    public function findDateByRoom($date, $room)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Date')
            ->createQueryBuilder('d')
            ->where('d.room = :room')
            ->andWhere('d.date = :date')
            ->orderBy('d.date', 'ASC')
            ->setParameter('room', $room)
            ->setParameter('date', $date)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
