<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HotelServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelServiceRepository extends EntityRepository
{
    /**
     * Get all blackout dates
     *
     * @return array
     */
    public function findByHotel($hid)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:HotelService')
            ->createQueryBuilder('hs')
            ->where('hs.hotel = :hotel')
            ->setParameter('hotel', $hid)
            ->orderBy('hs.name', 'ASC');
    }
}
