<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends EntityRepository
{

    /**
     * Get all hotels
     *
     * @return array
     */
    public function findAllHotels($vip)
    {
        $queryBuilder = $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Hotel')
            ->createQueryBuilder('h')
            ->select('h');
            

        if ($vip != true)
            $queryBuilder->where('h.vip = false');

        return $queryBuilder->orderBy('h.region, h.country, h.state, h.city', 'ASC')
            ->getQuery()
            ->getResult();
    }


    /**
     * Get invoice header & footer
     *
     * @return array
     */
    public function findRegions()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('h.region')
            ->from('GushhCoreBundle:Hotel', 'h')
            ->where('h.enabled = true')
            ->distinct()
            ->getQuery()
            ->getResult();
    }
    /**
     * Get invoice header & footer
     *
     * @return array
     */
    public function findStates($continent, $country = null, $limit = null, $vip = false)
    {
        $queryBuilder = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('h, COUNT(h.city) as HIDDEN cityCount')
            ->from('GushhCoreBundle:Hotel', 'h')
            ->where('h.continent = :continent')
            ->setParameter('continent', $continent)
            ->andWhere('h.enabled = true');

        if ($vip != true)
            $queryBuilder->andWhere('h.vip = false');

        if ($country)
            $queryBuilder->andWhere('h.country = :country')
                ->setParameter('country', $country);

        return
            $queryBuilder->groupBy('h.city')
            ->orderBy('cityCount', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function findEnabledHotelsBy($continent, $country, $state, $city, $hotel, $vip)
    {
        $queryBuilder = $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Hotel')
            ->createQueryBuilder('h')
            ->Where('h.continent = :continent')
            ->andWhere('h.enabled = true')
            ->setParameter('continent', $continent)
        ;
        
        if ($vip != true)
            $queryBuilder->andWhere('h.vip = false');


        if($country != '' && $country != 'EUROPE') {
            $queryBuilder->andWhere('h.country = :country')
                ->setParameter('country', $country)
            ;
        }
        if($state != '') {
            $queryBuilder->andWhere('h.state = :state')
                ->setParameter('state', $state)
            ;
        }
        if($city != '') {
            if (strtolower($state) == 'florida') {
                if(strtolower($city) == 'orlando') {
                    $queryBuilder->andWhere('h.city = :city')->setParameter('city', $city);
                }
                else {
                    $queryBuilder->andWhere('h.city <> :city')->setParameter('city', 'Orlando');
                }
            }
            else {
                $queryBuilder->andWhere('h.city = :city')->setParameter('city', $city);
            }
        }
        if($hotel != '') {
            $queryBuilder->andWhere('h.name = :hotel')
                ->setParameter('hotel', $hotel)
            ;
        }


        return $queryBuilder->getQuery()
            ->getResult();
    }
}
