<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionConditionRepository extends EntityRepository
{
    /**
     * Get all blackout dates
     *
     * @return array
     */
    public function findPromotionAndGroup($promotionId, $groupId)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:PromotionCondition')
            ->createQueryBuilder('p')
            ->where('p.promotion = :promotion')
            ->andWhere('p.expression = :group')
            ->setParameter('promotion', $promotionId)
            ->setParameter('group', $groupId)
            ->orderBy('p.id', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
