<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{

    /**
     * Get all promotions for a room
     *
     * @return array
     */
    public function findByRoom($rid)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Promotion')
            ->createQueryBuilder('p')
            ->where('p.room = :room')
            ->setParameter('room', $rid)
            ->orderBy('p.name', 'ASC');
    }
}
