<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionBenefitTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionBenefitTypeRepository extends EntityRepository
{

  /**
   * Get all blackout dates
   *
   * @return array 
   */
  public function findGroup($group)
  {

    return $this->getEntityManager()
                  ->getRepository('GushhCoreBundle:PromotionBenefitType')
                  ->createQueryBuilder('p')
                  ->where('p.group = :group')
                  ->setParameter('group', $group)
                  ->orderBy('p.name', 'ASC');
  }
}
