<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionConditionConditionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionConditionConditionalRepository extends EntityRepository
{

  /**
   * Get all blackout dates
   *
   * @return array 
   */
  public function findGroup($group)
  {

    return $this->getEntityManager()
                ->getRepository('GushhCoreBundle:PromotionConditionConditional')
                ->createQueryBuilder('p')
                ->where('p.group = :group')
                ->setParameter('group', $group)
                ->orderBy('p.name', 'ASC');
  }
}
