<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends EntityRepository
{
    /**
     * Get all blackout dates
     *
     * @return array
     */
    public function findByRoom($rid)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Rate')
            ->createQueryBuilder('r')
            ->where('r.room = :room')
            ->andWhere('r.enabled=true')
            ->setParameter('room', $rid)
            ->orderBy('r.name', 'ASC');
    }
}
