<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationPaymentStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationPaymentStatusRepository extends EntityRepository
{
    /**
     * Get all Conditions of specific group
     *
     * @return array
     */
    public function findAll()
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:ReservationPaymentStatus')
            ->createQueryBuilder('rps')
            ->orderBy('rps.id', 'ASC');
    }
}
