<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    /**
     * Get all reservations for the operator
     *
     * @return array
     */
    public function findByOperator($operator)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Reservation')
            ->createQueryBuilder('r')
            ->innerJoin('r.checkOutProcess', 'co', Join::WITH, 'r.id=co.reservation')
            ->innerJoin('co.search', 's', Join::WITH, 's.id = co.search')
            ->where('r.operator = :operator')
            ->setParameter('operator', $operator)
            ->orderBy('s.checkIn', 'DESC')
            ->getQuery()->getResult();
    }
    /**
     * Get all reservations for the agency
     *
     * @return array
     */
    public function findByAgency($agency)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Reservation')
            ->createQueryBuilder('r')
            ->innerJoin('r.checkOutProcess', 'co', Join::WITH, 'co.reservation = r.id')
            ->innerJoin('co.search', 's', Join::WITH, 's.id = co.search')
            ->innerJoin('co.user', 'u', Join::WITH, 'co.user = u.id')
            ->where('u.agency = :agency')
            ->setParameter('agency', $agency)
            ->orderBy('s.checkIn', 'DESC')
            ->getQuery()->getResult();
    }

    /**
     * Get all reservations
     *
     * @return array
     */
    public function findAll()
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Reservation')
            ->createQueryBuilder('r')
            ->innerJoin('r.checkOutProcess', 'co', Join::WITH, 'co.reservation = r.id')
            ->innerJoin('co.search', 's', Join::WITH, 's.id = co.search')
            ->orderBy('s.checkIn', 'DESC')
            ->getQuery()->getResult();
    }
}
