<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationStatusRepository extends EntityRepository
{
    /**
     * Get all Conditions of specific group
     *
     * @return array
     */
    public function findAll()
    {

        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:ReservationStatus')
            ->createQueryBuilder('rs')
            ->orderBy('rs.id', 'ASC');
    }
}
