<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoomServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomServiceRepository extends EntityRepository
{
    /**
     * Get all services for the room
     *
     * @return array
     */
    public function findByRoom($rid)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:RoomService')
            ->createQueryBuilder('rs')
            ->where('rs.room = :room')
            ->setParameter('room', $rid)
            ->orderBy('rs.name', 'ASC');
    }
}
