<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends EntityRepository
{
    /**
     * Get all rooms by hotel and capacity
     *
     * @return array
     */
    public function findByHotelAndCapacity($hotel, $pax)
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:Room')
            ->createQueryBuilder('r')
            ->where('r.capacity >= :pax')
            ->andWhere('r.enabled = true')
            ->andWhere('r.hotel = :hotel')
            ->setParameters(['pax' => $pax, 'hotel' => $hotel])
            ->getQuery()
            ->getResult();
    }
}
