<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchRepository extends EntityRepository
{
    public function findSearchBy($region, $continent, $country, $state, $city, $hotel, $scode, $user)
    {
        try {
            return $this->getEntityManager()
                ->getRepository('GushhCoreBundle:Search')
                ->createQueryBuilder('s')
                ->where('s.code = :code')
                ->andWhere('s.region = :region')
                ->andWhere('s.continent = :continent')
                ->andWhere('s.country = :country')
                ->andWhere('s.state = :state')
                ->andWhere('s.city = :city')
                ->andWhere('s.hotel = :hotel')
//                ->andWhere('s.user = :user')
                ->setParameter('code', $scode)
                ->setParameter('region', $region)
                ->setParameter('continent', $continent)
                ->setParameter('country', $country)
                ->setParameter('state', $state)
                ->setParameter('city', $city)
                ->setParameter('hotel', $hotel)
//                ->setParameter('user', $user)
                ->getQuery()
                ->getOneOrNullResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            // Handle the exception here. In this case, we are setting the variable to NULL
            return null;
        }
    }
}
