<?php

namespace Gushh\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     *
     * @return array
     */
    public function findAll()
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:User')
            ->createQueryBuilder('u')
            ->getQuery()
            ->getResult();
    }
    /**
     *
     * @return array
     */
    public function findAllEnabled()
    {
        return $this->getEntityManager()
            ->getRepository('GushhCoreBundle:User')
            ->createQueryBuilder('u')
            ->where('u.enabled=1')
            ->getQuery()
            ->getResult();
    }
    /**
     * @param string $role
     *
     * @return array
     */
    public function findByRole($role)
    {
        $qb = $this->getEntityManager()
            ->getRepository('GushhCoreBundle:User')
            ->createQueryBuilder('u')
            ->where('u.roles LIKE :role')
            ->andWhere('u.enabled=1')
            ->setParameter('role', '%"' . $role . '"%');

        return $qb->getQuery()->getResult();
    }

    /**
     * @param array $roles
     *
     * @return array
     */
    public function findByRoles($roles)
    {
        $qb = $this->getEntityManager()
            ->getRepository('GushhCoreBundle:User')
            ->createQueryBuilder('u')
            ->where('u.roles LIKE :role1')
            ->orWhere('u.roles LIKE :role2')
            ->andWhere('u.enabled=1')
            ->setParameter('role1', '%"' . $roles[0] . '"%')
            ->setParameter('role2', '%"' . $roles[1] . '"%');

        return $qb->getQuery()->getResult();
    }

}
